# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(870, 543)
        Dialog.setTabletTracking(True)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 971, 645))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(590, 10, 181, 31))
        self.textEdit.setObjectName("textEdit")
        self.Ds_pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.Ds_pushButton_2.setGeometry(QtCore.QRect(780, 90, 75, 23))
        self.Ds_pushButton_2.setObjectName("Ds_pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(530, 90, 61, 31))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(530, 10, 61, 31))
        self.label.setObjectName("label")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(590, 90, 181, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.Ds_pushButton = QtWidgets.QPushButton(self.tab)
        self.Ds_pushButton.setGeometry(QtCore.QRect(780, 10, 75, 23))
        self.Ds_pushButton.setObjectName("Ds_pushButton")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(530, 150, 61, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(630, 150, 61, 31))
        self.label_4.setObjectName("label_4")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(560, 150, 51, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(99999)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_2.setGeometry(QtCore.QRect(670, 150, 51, 22))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(99999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(740, 160, 47, 16))
        self.label_5.setObjectName("label_5")
        self.spinBox_3 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_3.setGeometry(QtCore.QRect(800, 150, 42, 22))
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(99999)
        self.spinBox_3.setObjectName("spinBox_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(530, 440, 341, 81))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(530, 420, 171, 16))
        self.label_6.setObjectName("label_6")
        self.Ds_pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.Ds_pushButton_3.setGeometry(QtCore.QRect(800, 410, 75, 23))
        self.Ds_pushButton_3.setObjectName("Ds_pushButton_3")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_6.setGeometry(QtCore.QRect(10, 0, 511, 531))
        self.textEdit_6.setReadOnly(True)
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(530, 180, 81, 31))
        self.label_12.setObjectName("label_12")
        self.spinBox_6 = QtWidgets.QSpinBox(self.tab)
        self.spinBox_6.setGeometry(QtCore.QRect(620, 180, 42, 21))
        self.spinBox_6.setMinimum(1)
        self.spinBox_6.setMaximum(100)
        self.spinBox_6.setProperty("value", 1)
        self.spinBox_6.setObjectName("spinBox_6")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_4.setGeometry(QtCore.QRect(590, 50, 181, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(530, 50, 61, 31))
        self.label_13.setObjectName("label_13")
        self.Ds_pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.Ds_pushButton_4.setGeometry(QtCore.QRect(780, 50, 75, 23))
        self.Ds_pushButton_4.setObjectName("Ds_pushButton_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(10, 0, 531, 521))
        self.textBrowser.setObjectName("textBrowser")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(550, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_3.setGeometry(QtCore.QRect(590, 110, 201, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.Re_pushButton = QtWidgets.QPushButton(self.tab_2)
        self.Re_pushButton.setGeometry(QtCore.QRect(800, 120, 75, 23))
        self.Re_pushButton.setObjectName("Re_pushButton")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(550, 420, 321, 101))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(550, 220, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setGeometry(QtCore.QRect(740, 220, 111, 41))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.Re_pushButton2 = QtWidgets.QPushButton(self.tab_2)
        self.Re_pushButton2.setGeometry(QtCore.QRect(800, 390, 75, 23))
        self.Re_pushButton2.setObjectName("Re_pushButton2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(660, 219, 71, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(550, 0, 256, 41))
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.Re_pushButton3 = QtWidgets.QPushButton(self.tab_2)
        self.Re_pushButton3.setEnabled(False)
        self.Re_pushButton3.setGeometry(QtCore.QRect(800, 180, 75, 23))
        self.Re_pushButton3.setObjectName("Re_pushButton3")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setEnabled(True)
        self.label_16.setGeometry(QtCore.QRect(550, 160, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_7.setEnabled(False)
        self.textEdit_7.setGeometry(QtCore.QRect(590, 170, 201, 31))
        self.textEdit_7.setObjectName("textEdit_7")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 0, 531, 521))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_5.setGeometry(QtCore.QRect(590, 10, 201, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.RC_pushButton = QtWidgets.QPushButton(self.tab_3)
        self.RC_pushButton.setGeometry(QtCore.QRect(800, 20, 75, 23))
        self.RC_pushButton.setObjectName("RC_pushButton")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(550, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spinBox_4 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_4.setGeometry(QtCore.QRect(730, 90, 51, 41))
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(540, 60, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(540, 140, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.spinBox_5 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_5.setGeometry(QtCore.QRect(730, 160, 51, 41))
        self.spinBox_5.setObjectName("spinBox_5")
        self.RC_pushButton2 = QtWidgets.QPushButton(self.tab_3)
        self.RC_pushButton2.setGeometry(QtCore.QRect(800, 240, 75, 23))
        self.RC_pushButton2.setObjectName("RC_pushButton2")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_4.setGeometry(QtCore.QRect(550, 420, 321, 101))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 0, 531, 521))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(550, 10, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.FT_textEdit_1 = QtWidgets.QTextEdit(self.tab_4)
        self.FT_textEdit_1.setGeometry(QtCore.QRect(590, 40, 201, 31))
        self.FT_textEdit_1.setObjectName("FT_textEdit_1")
        self.FT_pushButton_1 = QtWidgets.QPushButton(self.tab_4)
        self.FT_pushButton_1.setGeometry(QtCore.QRect(800, 50, 75, 23))
        self.FT_pushButton_1.setObjectName("FT_pushButton_1")
        self.FT_pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.FT_pushButton_2.setGeometry(QtCore.QRect(800, 140, 75, 23))
        self.FT_pushButton_2.setObjectName("FT_pushButton_2")
        self.FT_textEdit_2 = QtWidgets.QTextEdit(self.tab_4)
        self.FT_textEdit_2.setGeometry(QtCore.QRect(590, 130, 201, 31))
        self.FT_textEdit_2.setObjectName("FT_textEdit_2")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(550, 90, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.FT_pushButton_3 = QtWidgets.QPushButton(self.tab_4)
        self.FT_pushButton_3.setGeometry(QtCore.QRect(800, 290, 75, 23))
        self.FT_pushButton_3.setObjectName("FT_pushButton_3")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_6.setGeometry(QtCore.QRect(550, 320, 321, 201))
        self.textBrowser_6.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setGeometry(QtCore.QRect(720, 290, 73, 16))
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "DataTools"))
        self.Ds_pushButton_2.setText(_translate("Dialog", "Save"))
        self.label_2.setText(_translate("Dialog", "Save Path"))
        self.label.setText(_translate("Dialog", "Image Path"))
        self.Ds_pushButton.setText(_translate("Dialog", "Content"))
        self.label_3.setText(_translate("Dialog", "Start"))
        self.label_4.setText(_translate("Dialog", "End"))
        self.label_5.setText(_translate("Dialog", "Iteration"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Class 0 with_mask\n"
"Class 1 without_mask\n"
"Class 2 incorrect_mask"))
        self.label_6.setText(_translate("Dialog", "Example Class Information"))
        self.Ds_pushButton_3.setText(_translate("Dialog", "START"))
        self.textEdit_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                  _    _     _        _____ _                 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |  | |   (_)      / ____| |                </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |__| |___ _ _ __ | |    | |__  _   _ _ __  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 |  __  / __| | \'_ \\| |    | \'_ \\| | | | \'_ \\ </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |  | \\__ \\ | | | | |____| | | | |_| | | | |</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 |_|  |_|___/_|_| |_|\\_____|_| |_|\\__,_|_| |_|</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "Class Number"))
        self.label_13.setText(_translate("Dialog", "Labels Path"))
        self.Ds_pushButton_4.setText(_translate("Dialog", "Content"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Datasplict"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                  _    _     _        _____ _                 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |  | |   (_)      / ____| |                </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |__| |___ _ _ __ | |    | |__  _   _ _ __  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 |  __  / __| | \'_ \\| |    | \'_ \\| | | | \'_ \\ </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |  | \\__ \\ | | | | |____| | | | |_| | | | |</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 |_|  |_|___/_|_| |_|\\_____|_| |_|\\__,_|_| |_|</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "Path"))
        self.Re_pushButton.setText(_translate("Dialog", "content"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Rename Example :  </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ASD.JPG         1.JPG</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">qwe.JPG      →      2.JPG</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">qweqas.JPG         3.JPG</p></body></html>"))
        self.label_8.setText(_translate("Dialog", "NewName"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", ".txt"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", ".jpg"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.Re_pushButton2.setText(_translate("Dialog", "START"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("Dialog", "Onlyone"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("Dialog", "Images and Labels"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.Re_pushButton3.setText(_translate("Dialog", "content"))
        self.label_16.setText(_translate("Dialog", "Path"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Rename"))
        self.textBrowser_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                  _    _     _        _____ _                 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |  | |   (_)      / ____| |                </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |__| |___ _ _ __ | |    | |__  _   _ _ __  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 |  __  / __| | \'_ \\| |    | \'_ \\| | | | \'_ \\ </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |  | \\__ \\ | | | | |____| | | | |_| | | | |</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 |_|  |_|___/_|_| |_|\\_____|_| |_|\\__,_|_| |_|</span></p></body></html>"))
        self.RC_pushButton.setText(_translate("Dialog", "content"))
        self.label_9.setText(_translate("Dialog", "Path"))
        self.label_10.setText(_translate("Dialog", "Orinignal Class Number"))
        self.label_11.setText(_translate("Dialog", "Replacel Class Number"))
        self.RC_pushButton2.setText(_translate("Dialog", "START"))
        self.textBrowser_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Example :  </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">if want replace  labels   1 with 2 .</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">should be set number Orinignal class number 1 and replace class number 2   </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 x1,y1 x2,y2    →  2 x1,y1 x2,y2  </p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "ReplaceClass"))
        self.textBrowser_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                  _    _     _        _____ _                 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |  | |   (_)      / ____| |                </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |__| |___ _ _ __ | |    | |__  _   _ _ __  </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 |  __  / __| | \'_ \\| |    | \'_ \\| | | | \'_ \\ </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 | |  | \\__ \\ | | | | |____| | | | |_| | | | |</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'Courier New\'; color:#000000; background-color:#ffffff;\">                 |_|  |_|___/_|_| |_|\\_____|_| |_|\\__,_|_| |_|</span></p></body></html>"))
        self.label_14.setText(_translate("Dialog", "Path"))
        self.FT_pushButton_1.setText(_translate("Dialog", "content"))
        self.FT_pushButton_2.setText(_translate("Dialog", "content"))
        self.label_15.setText(_translate("Dialog", "SavePath"))
        self.FT_pushButton_3.setText(_translate("Dialog", "Start"))
        self.textBrowser_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">1.選擇圖片路徑或是標籤路徑。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">2.選擇要存檔的路徑 將自動產生  \'Train.txt\' </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    若已存在則會覆蓋刪除 請先檢查。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">10/18 update .. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">一但勾選YoLov3 則會產出 csv檔, </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">內會有[照片名稱][Xmin][Ymin][Xmax][Ymax]</span></p></body></html>"))
        self.checkBox.setText(_translate("Dialog", "YoLov3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "FileToList"))
